### PR TITLE
Add on-close action which corresponds to on-open.

### PR DESCRIPTION
**Pull request by cantsin**
With shiny test goodness.

### CODE REVIEW

**Comment by cantsin** [comment]
@taras I'm wondering if there is a better way to do this: 

https://github.com/LocusEnergy/ember-async-tree/blob/on-close-action/addon/components/async-tree.js#L137-L157

Seems like this could use some refactoring, no?

**Comment by taras** [comment]
It might be possible to do all of this with ember-composiable-helpers

-- 
Taras Mankovski

On March 21, 2016 at 11:53:59 AM, James Tranovich (notifications@github.com) wrote:

@taras I'm wondering if there is a better way to do this:

https://github.com/LocusEnergy/ember-async-tree/blob/on-close-action/addon/components/async-tree.js#L137-L157

Seems like this could use some refactoring, no?

**Comment by cantsin** [comment]
Can you clarify a bit? I'm still not sure how to override `on-open` or `on-close` from outside using `ember-composable-helpers`?

**Comment by taras** [comment]
Nevermind, it won't work as I thought. LGTM :)

**Pull request merged**
